### PR TITLE
Remove all reference to privilege dropping in favour of systemd

### PR DESCRIPTION
**Pull request by Rosuav**

### CODE REVIEW

**Comment by Rosuav** [comment]
I went through a few different ideas before settling on this one.

**Comment by MikeiLL** [comment]
Invalid argument for Main Glitch Server:

● glitch.service - Infinite Glitch
   Loaded: error (Reason: Invalid argument)
   Active: failed (Result: exit-code) since Tue 2016-12-27 10:07:36 EST; 1h 48min ago
 Main PID: 8093 (code=exited, status=1/FAILURE)

Are there other logs I should look at? This failure is from 2 hours ago, apparently.

I stopped both services and confirmed no python or ffmpeg were running with `top`. Re-ran `bash make service.sh`.

mike

**Comment by Rosuav** [comment]
It should be just `./makeservice.sh` and then restart the systemd services (`sudo systemctl restart glitch\*`).

**Comment by MikeiLL** [comment]
Produces following error:
`Failed to restart glitch.service: Unit glitch.service failed to load: Invalid argument. See system logs and 'systemctl status glitch.service' for details.`

**Comment by Rosuav** [comment]
And the logs say...?

**Comment by MikeiLL** [comment]
Well. No logs in the `home` or `glitch`. App directory only the `404.log`.

Daemon log just lists output from renderer as far as I can see:
```
Dec 27 18:29:24 indu python[9349]: 2016-12-27 13:29:24,449:INFO:glitch.database:Automatically picking track 13.
etc...
```
`syslog`:
```
Dec 27 18:32:07 indu python[9349]: 2016-12-27 13:32:07,552:INFO:root:Sending 32511400 bytes of data for 184.3049886621315 secs of 13 ChrisBradley.mp3
Dec 27 18:35:01 indu CRON[9847]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
```
`alternatives.log` doesn't look relevant.

`journalctl` returns "No journal files were found."

`auth.log`:
```
Dec 27 18:38:41 indu sudo: pam_unix(sudo:session): session opened for user root by mikekilmer(uid=0)
Dec 27 18:38:41 indu sudo: pam_unix(sudo:session): session closed for user root
```
`debug` is empty.

`btmp` looks like a lot of:
```
X{"?%ssh:nottyuser123.31.34.18۰bX{"?&ssh:nottysupport123.31.41.236??bX{)??&ssh:nottysupport123.31.41.236??bX{)
```
`dmesg`: "(Nothing has been logged yet.)"
`dpkg`:
```
2016-12-24 18:17:49 status half-configured yasm:amd64 1.2.0-dmo2
2016-12-24 18:17:49 status installed yasm:amd64 1.2.0-dmo2
2016-12-24 18:17:49 configure libopenjpeg-dev:amd64 1:1.5.2-3 <none>
2016-12-24 18:17:49 status unpacked libopenjpeg-dev:amd64 1:1.5.2-3
2016-12-24 18:17:49 status half-configured libopenjpeg-dev:amd64 1:1.5.2-3
2016-12-24 18:17:49 status installed libopenjpeg-dev:amd64 1:1.5.2-3
2016-12-24 18:17:49 trigproc libc-bin:amd64 2.19-18+deb8u6 <none>
2016-12-24 18:17:49 status half-configured libc-bin:amd64 2.19-18+deb8u6
2016-12-24 18:17:49 status installed libc-bin:amd64 2.19-18+deb8u6
2016-12-24 18:17:49 startup packages configure
```
`faillog` is empty.

`kernlog` has nothing for today. Yesterday:
```
Dec 26 17:28:09 indu kernel: [31338]  1000 31338     5832        1      16       3      493             0 bash
Dec 26 17:28:09 indu kernel: [31390]  1000 31390     5836        1      16       3      497             0 bash
Dec 26 17:28:09 indu kernel: [32208]  1000 32208    40054      592      80       3     5148             0 python
Dec 26 17:28:09 indu kernel: [32210]   108 32210    58652      598      66       3      560             0 postgres
Dec 26 17:28:09 indu kernel: [  460]  1000   460   748521   480351    1396       6    94875             0 python
Dec 26 17:28:09 indu kernel: [  465]   108   465    58536      708      66       3      373             0 postgres
Dec 26 17:28:09 indu kernel: [  844]  1000   844     4315       81      14       3        0             0 tmux
Dec 26 17:28:09 indu kernel: Out of memory: Kill process 460 (python) score 897 or sacrifice child
Dec 26 17:28:09 indu kernel: Killed process 460 (python) total-vm:2994084kB, anon-rss:1920588kB, file-rss:816kB, shmem-rss:0kB
Dec 26 17:28:09 indu kernel: oom_reaper: reaped process 460 (python), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```
`messages`:
```
Dec 27 06:27:38 indu rsyslogd0: action 'action 17' resumed (module 'builtin:ompipe') [try http://www.rsyslog.com/e/0 ]
Dec 27 06:27:38 indu rsyslogd-2359: action 'action 17' resumed (module 'builtin:ompipe') [try http://www.rsyslog.com/e/2359 ]
Dec 27 15:05:56 indu rsyslogd-2007: action 'action 17' suspended, next retry is Tue Dec 27 15:06:26 2016 [try http://www.rsyslog.com/e/2007 ]
```
There's probably a log I'm not finding. Content of `/var/log/`:

```
├── alternatives.log
├── apt
│   ├── history.log
│   └── term.log
├── auth.log
├── auth.log.1
├── btmp
├── daemon.log
├── daemon.log.1
├── debug
├── debug.1
├── dmesg
├── dpkg.log
├── exim4 [error opening dir]
├── faillog
├── fontconfig.log
├── fsck
│   ├── checkfs
│   └── checkroot
├── installer
│   ├── cdebconf
│   │   ├── questions.dat
│   │   └── templates.dat
│   ├── hardware-summary
│   ├── lsb-release
│   ├── partman
│   ├── status
│   └── syslog
├── kern.log
├── kern.log.1
├── lastlog
├── messages
├── messages.1
├── postgresql
│   └── postgresql-9.4-main.log
├── syslog
├── syslog.1
├── syslog.2.gz
├── syslog.3.gz
├── sysstat
└── wtmp

```

**Comment by MikeiLL** [comment]
Not sure if this will be useful at all, but when running the two servers separately here on the dev box, the following output was printed in the renderer terminal:

```
Renderer listening on 0.0.0.0:8889
```
followed by a whole bunch of:
```
/Users/mikekilmer/Docker/Glitch/appension/env/lib/python3.5/site-packages/numpy/core/numeric.py:482: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return array(a, dtype, copy=False, order=order)
```
Finally 
```
ERROR:asyncio:Fatal write error on socket transport
protocol: <RequestHandler GET:/status.json connected>
transport: <_SelectorSocketTransport fd=23 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 707, in write
    n = self._sock.send(data)
OSError: [Errno 41] Protocol wrong type for socket
```

I think it's timing out, at least in this case, awaiting ffmpeg. Am I calling it wrong?

http://stackoverflow.com/questions/38741219/aiohttp-fatal-read-error-on-socket-transport-timeouterror

**Pull request merged**
