### PR TITLE
More itrim/otrim work

### PR DESCRIPTION
**Pull request by Rosuav**

### CODE REVIEW

**Comment by Rosuav** [comment]
There's a rejig of `__main__` in there.

**Comment by Rosuav** [comment]
As of this point in the commits, it's now possible to listen to a specific transition. Invoke the renderer:

    $ python3 -m glitch audition 123 234 outputfile.mp3

and then play the resultant MP3 file.

Next step: Make it possible to do this from the web, without amassing innumerable junk MP3 files.

**Comment by MikeiLL** [comment]
Added form fields to blindly edit itrim and otrim on the individual track edit pages. Accidentally committed it when committing an addition to the README. We still have template pages for `manage_transition` and `audition` which might be useful. It might be easiest to just use the previous approach of pulling up the next _active_ track in the sequence (or if sequence is 0, next available ID) as track number two for now, and possibly add the choice of any two tracks later on. But could certainly be convinced otherwise. 

If we did want to allow admin to audition transitions between any two tracks, one way to do it would be to add an intermediary step in the transition process which would be to—possibly default to the next track on sequence (or if sequence is 0, next available ID), but have a select field to chose a different track to transition against.

That makes me wonder if we wouldn't just want to have our own form which displays TWO select fields for track1 and track2. Possibly would want to also allow the admin to set sequence within the transition page, but that might require also allowing the admin to view available sequence slots or something along those lines.

Ideally they would be able to view a zoom-able wave image of the whole major glitch with handles at the beginning and end of each track, playable at any point within the track, but that ain't tomorrow and probably not even this year!

I'm trying to figure out how to request psql to return the _next_ track _greater than_ the _given_ track, based on _sequence_, with a status of _active_. Then I think we could fairly easily reproduce the old transition management, minus crossfading.

**Comment by Rosuav** [comment]
`select id, sequence from tracks where sequence >= %s and id != %s order by sequence limit 1`

**Pull request merged**
